name: pokemon
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  provider: ^6.0.5
  wear: ^1.1.0
  wearable_rotary: ^2.0.1
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
